version: "3"
services:
    # Web
    web:
        image: nginx
        volumes:
            - ".:/app"
            - "./docker_dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
            - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        depends_on:
            - php
        ports:
            - "8000:80"
    php:
        build:
            context: .
            dockerfile: docker_dev/Dockerfile
        volumes:
            - ".:/app"
            - "./docker_dev/php.ini:/usr/local/etc/php/conf.d/custom.ini"
        depends_on:
            - db
    db:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db

volumes:
    mongodb_data_container: